# Generated by Django 3.2.7 on 2021-09-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210924_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='article',
        ),
    ]
