# Generated by Django 3.2.7 on 2021-09-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_image_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='subtitle',
            new_name='subcategory',
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
