# Generated by Django 3.2.7 on 2021-09-26 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_promotions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promotions',
            new_name='Promotion',
        ),
    ]
